# Generated by Django 5.2.5 on 2025-08-09 05:35

import apps.catalog.models.BookModel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "book_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("isbn", models.CharField(max_length=13)),
                ("title", models.CharField(max_length=40)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("stock_quantity", models.PositiveIntegerField()),
                (
                    "cover_url",
                    models.ImageField(
                        upload_to=apps.catalog.models.BookModel.media_upload_path
                    ),
                ),
                ("published_date", models.DateField()),
                ("avg_rating", models.FloatField()),
                ("category", models.ManyToManyField(to="catalog.category")),
            ],
        ),
    ]
