# Generated by Django 5.2.5 on 2025-08-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genra",
            field=models.CharField(
                choices=[
                    ("Classic", "Classic"),
                    ("kids", "Kids"),
                    ("Mature", "Mature"),
                    ("Thrillers", "Thrillers"),
                    ("Textbooks", "Textbooks"),
                ],
                default="",
                null=True,
            ),
        ),
    ]
